# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7abc67f7176de5364c94609ef4e47fd9e523f3f58d0b181141dfe19fc0271a81eccd1cb3fa64407b0de5db642498f59d1b1ab88342ae8ff977da8510a0266b86

test:
  secret_key_base: 04d63495bcab594159e5b821bc81b1de625b94ffb9f4a7f7d726037f95eddd6c22d1e44dac39f9c615366aa6d14c77396205a54444c51f41dd3bb7089c18a1b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
